# Generated by Django 5.1.2 on 2024-11-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_start_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10),
            preserve_default=False,
        ),
    ]
