# Generated by Django 5.1.2 on 2024-11-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closed',
            name='user',
        ),
    ]
