# Generated by Django 5.1.2 on 2024-11-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_closed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.TextField(default='', max_length=50),
        ),
    ]
