# Generated by Django 5.1.2 on 2024-11-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.TextField(default='thing', max_length=50),
        ),
    ]
